default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE_NAME: meal-provider-frontend
  TAG: $CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA
  FULL_IMAGE_PATH: ${CTR_REGISTRY_HOST}/${PROJECT_ID}/${CTR_REPOSITORY}/${IMAGE_NAME}:${TAG}

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker info
    - echo $GCLOUD_SERVICE_KEY | base64 -d -i | docker login -u _json_key --password-stdin ${CTR_REGISTRY_HOST}
    - docker build -t ${FULL_IMAGE_PATH} .
    - docker push ${FULL_IMAGE_PATH}
  only:
    - master
    - develop

deploy:
  stage: deploy
  script:
    - echo $GCLOUD_SERVICE_KEY | base64 -d -i | docker login -u _json_key --password-stdin ${CTR_REGISTRY_HOST}
    - docker pull ${FULL_IMAGE_PATH}
    - docker run -d ${FULL_IMAGE_PATH}
  only:
    - master
