stages:
  - deploy

variables:
  DOCKER_HOST: "tcp://docker:2375" # Set Docker host to communicate with the DinD service

services:
  - docker:19.03.12-dind

docker_push:
  stage: deploy
  tags:
    - docker
    - cn
  image: google/cloud-sdk:latest
  variables:
    IMAGE_NAME: meal-provider-frontend
    TAG: $CI_COMMIT_SHA
    FULL_IMAGE_PATH: ${CTR_REGISTRY_HOST}/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${TAG}
  before_script:
    # Decode and save the service account key file
    - echo $GCLOUD_SERVICE_KEY | base64 --decode -i > ${CI_PROJECT_DIR}/gcloud-service-key.json
    # Authenticate with Google Cloud
    - gcloud auth activate-service-account --key-file=${CI_PROJECT_DIR}/gcloud-service-key.json
    - gcloud --quiet config set project $PROJECT_ID
    # Configure Docker to use Google Artifact Registry
    - gcloud auth configure-docker ${CTR_REGISTRY_HOST}
  script:
    - docker pull alpine:latest
    - docker tag alpine:latest ${FULL_IMAGE_PATH}
    - docker push ${FULL_IMAGE_PATH}
