apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: whoami-propagation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: whoami-deployment
    - apiVersion: v1
      kind: Service
      name: whoami-service
    - apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute
      name: http-whoami
  placement:
    clusterAffinity:
      clusterNames:
        - cn-gke-1
        - cn-gke-2
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - cn-gke-1
            weight: 1
          - targetCluster:
              clusterNames:
                - cn-gke-2
            weight: 1
